apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: node-express-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: v15hnupm/node-express-mongodb:latest  # ✅ Correct image name
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          value: "mongodb://root:example@mongo-service:27017/mydatabase"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
