apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: node-express-mongodb
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGODB_URI: "mongodb://root:example@mongo-service:27017/mydatabase"
