apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-app-db-pvc
  namespace: flask-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
