apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: django-notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: v15hnupm/django-notes-app:latest
        ports:
        - containerPort: 8000
        command: ["/bin/sh"]
        args: ["-c", "gunicorn notesapp.wsgi --bind 0.0.0.0:8000"]
        env:
        - name: DATABASE_HOST
          value: "mysql-service"
        - name: DATABASE_NAME
          value: "test_db"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "root"
        - name: DATABASE_PORT
          value: "3306"
        - name: DJANGO_SETTINGS_MODULE
          value: "notesapp.settings"
        - name: DEBUG
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
